### ISSUE TITLE
Warnings from pip caching steps on CI

### ISSUE THREAD

**Issue by sajith** [atlanticwave-sdx/sdx-controller#107]
Take https://github.com/atlanticwave-sdx/sdx-controller/actions/runs/3595063504, for example.  There are repeated warnings about the workflow:

```
The `set-output` command is deprecated and will be disabled
soon. Please upgrade to using Environment Files. For more
information see:
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

This is from  steps where we set up pip cache; there's probably an easier and up-to-date way of setting up pip cache available in [actions/setup-python@v4](https://github.com/actions/setup-python), like so:

```yaml
- uses: actions/setup-python@v4
  with:
    python-version: '3.9'
    cache: 'pip' # caching pip dependencies
```
